batch_size = 64
steps = 10000
print_every = 500
seed = 1
cnn_storage = "./res/cnn.eqx"
googlenet = true

[[sae]]
googlenet = true
layer = 6
hidden_size = 200000
input_size = 94080
learning_rate = 1e-4
l1 = 3e-4
