batch_size = 64
steps = 10000
print_every = 500
seed = 1
cnn_storage = "/home/jo3/p/sparse_autoencoder/sparse_autoencoder/../res/cnn.eqx"
sae = [
    { layer = 6, hidden_size = 256, input_size = 64, learning_rate = 0.0001, l1 = 0.0003 },
]
